version: "3.9"

services:
  server:
    build: .
    ports:
      - "8080:8080"

  db:
    image: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
